import puppeteer from 'puppeteer-core';
import fs from 'fs';
const CHROME = 'C:/Program Files/Google/Chrome/Application/chrome.exe';
const GAS = process.argv[2] || 'https://script.google.com/macros/s/AKfycbxXYlKJfozMft9Mi-02GmcBl0ANjNGra8mw5B6xERgqqkt-zc4ya1PyXstAhga9snFA/exec';
const browser = await puppeteer.launch({ executablePath: CHROME, headless: 'new', args: ['--no-sandbox', '--disable-dev-shm-usage'] });
const page = await browser.newPage();
await page.setViewport({ width: 1440, height: 900 });
await page.goto(GAS, { waitUntil: 'load', timeout: 120000 }).catch(() => {});
await new Promise(r => setTimeout(r, 4000));
const html = await page.content();
console.log('HTML length:', html.length);
const idx = html.indexOf('notifPaginationFooter');
console.log('has notifPaginationFooter:', idx !== -1);
if (idx !== -1) console.log('context:', html.substring(idx - 300, idx + 200).replace(/\s+/g, ' '));
const rightIdx = html.indexOf('right: -420px');
console.log('has right:-420px CSS:', rightIdx !== -1);
const r2 = html.indexOf('right:-420px');
console.log('has right:-420px (no space):', r2 !== -1);
const panelIdx = html.indexOf('.notification-panel');
console.log('notification-panel CSS ctx:', panelIdx !== -1 ? html.substring(panelIdx, panelIdx + 250).replace(/\s+/g, ' ') : '');
fs.writeFileSync('C:/Users/afsar/AppData/Local/Temp/opencode/live_gas_source.html', html);
await browser.close();
