var WHATSAPP = {
  SHEET: 'WhatsAppLogs',
  TEMPLATES_SHEET: 'WhatsAppTemplates',
  FIELDS: ['MessageID','DateTime','Recipient','PhoneNumber','Module','ReferenceID','Template','Status','Provider','ErrorMessage','SentBy','IdempotencyKey'],
  SETTINGS: {
    ENABLED: 'whatsapp_enabled',
    COMPANY_NAME: 'whatsapp_company_name',
    DEFAULT_COUNTRY_CODE: 'whatsapp_default_country_code',
    PROVIDER: 'whatsapp_provider',
    API_ENDPOINT: 'whatsapp_api_endpoint',
    API_TOKEN: 'whatsapp_api_token',
    PHONE_NUMBER_ID: 'whatsapp_phone_number_id',
    BUSINESS_ACCOUNT_ID: 'whatsapp_business_account_id',
    TEST_PHONE: 'whatsapp_test_phone',
    TEST_MESSAGE: 'whatsapp_test_message',
    META_API_ENDPOINT: 'whatsapp_meta_api_endpoint',
    META_API_TOKEN: 'whatsapp_meta_api_token',
    META_PHONE_NUMBER_ID: 'whatsapp_meta_phone_number_id',
    META_BUSINESS_ACCOUNT_ID: 'whatsapp_meta_business_account_id',
    TWILIO_API_ENDPOINT: 'whatsapp_twilio_api_endpoint',
    TWILIO_API_TOKEN: 'whatsapp_twilio_api_token',
    TWILIO_PHONE_NUMBER_ID: 'whatsapp_twilio_phone_number_id',
    TWILIO_BUSINESS_ACCOUNT_ID: 'whatsapp_twilio_business_account_id',
    ULTRAMSG_API_URL: 'whatsapp_ultramsg_api_url',
    ULTRAMSG_INSTANCE_ID: 'whatsapp_ultramsg_instance_id',
    ULTRAMSG_TOKEN: 'whatsapp_ultramsg_token'
  },
  TWILIO_DEFAULTS: {
    API_ENDPOINT: 'https://api.twilio.com/2010-04-01'
  },
  ULTRAMSG_DEFAULTS: {
    API_URL: 'https://api.ultramsg.com'
  },
  DEFAULTS: {
    COMPANY_NAME: 'PWI CMMS',
    DEFAULT_COUNTRY_CODE: '91',
    PROVIDER: 'meta',
    API_ENDPOINT: 'https://graph.facebook.com/v18.0',
    TEST_MESSAGE: 'Test message from PWI CMMS'
  },
  TEMPLATES: {
    JC_OPENED: 'JobOpened',
    JC_ASSIGNED: 'JobAssigned',
    JC_STARTED: 'JobStarted',
    JC_PENDING: 'JobPending',
    JC_CLOSED: 'JobClosed',
    JC_APPROVED: 'JobApproved',
    PM_DUE: 'PMDue',
    PM_OVERDUE: 'PMOverdue',
    LOW_STOCK: 'LowStock',
    OUT_OF_STOCK: 'OutOfStock',
    PURCHASE_REQUEST: 'PurchaseRequest',
    GOODS_RECEIPT: 'GoodsReceipt',
    USER_CREATED: 'UserCreated',
    PASSWORD_RESET: 'PasswordReset'
  },
  TEMPLATE_FIELDS: ['TemplateID','TemplateName','EventType','TemplateBody','Variables','CreatedBy','CreatedAt','UpdatedBy','UpdatedAt'],
  STATUS: { PENDING: 'Pending', SENT: 'Sent', FAILED: 'Failed' }
};

var WHATSAPP_JCE_SENT = {};

var WHATSAPP_JCE = {
  SEP: '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
  FOOTER_COMPANY: 'Pakistan Wire Industries',
  EVENTS: {
    JobOpened:   { label: 'Job Card Opened',   emoji: '🆕', timestamp: 'opened',   action: 'Job card opened and awaiting assignment', next: 'Technician to be assigned and maintenance started' },
    JobAssigned: { label: 'Job Card Assigned', emoji: '👤', timestamp: '',          action: 'Job card assigned to technician', next: 'Technician to start maintenance work' },
    JobPending:  { label: 'Job Card Pending Review', emoji: '⏳', timestamp: 'pending', action: 'Job submitted for supervisor review', next: 'Supervisor to review and approve' },
    JobStarted:  { label: 'Job Card Started',  emoji: '▶️', timestamp: 'started',   action: 'Maintenance work started', next: 'Complete repair and submit for review' },
    JobApproved: { label: 'Job Card Approved', emoji: '✅', timestamp: 'approved',  action: 'Job approved and closed out', next: 'None - job complete' },
    JobClosed:   { label: 'Job Card Closed',   emoji: '🔒', timestamp: 'closed',    action: 'Job closed after completion', next: 'None - job complete' }
  },
  TEMPLATE_BODIES: {
    JobOpened: [
      '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
      '🆕 *JOB CARD OPENED*',
      '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
      '🏢 *{{companyName}}*',
      '',
      '*JOB CARD INFORMATION*',
      '📇 Job Card: {{jobCardNo}}',
      '📊 Status: {{currentStatus}}',
      '📅 Opened: {{opened}}',
      '',
      '*MAINTENANCE DETAILS*',
      '🏭 Section: {{section}}',
      '🏗️ Department: {{department}}',
      '⚙️ Machine: {{machine}}',
      '🔢 Machine Number: {{machineNumber}}',
      '📌 Machine ID: {{machineId}}',
      '🔖 Asset ID: {{assetId}}',
      '🏷️ Category: {{category}}',
      '⚠️ *Issue:* {{issue}}',
      '🎯 Priority: {{priority}}',
      '',
      '*RESPONSIBILITY*',
      '🛠️ Maintenance Team: {{maintenanceTeam}}',
      '🧑‍🔧 Reported By: {{reportedBy}}',
      '👤 Assigned To: {{assignedTo}}',
      '',
      '*ACTION*',
      '🆕 Job card opened and awaiting assignment',
      '📝 Remarks: {{initialRemarks}}',
      '',
      '*SYSTEM*',
      '💾 Created By: {{createdBy}}',
      '🔔 Notification: Job Card Opened',
      '',
      '*NEXT ACTION*',
      '🎯 Technician to be assigned and maintenance started',
      '',
      '🤖 Generated by {{companyName}} | 🏢 Pakistan Wire Industries',
      '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━'
    ].join('\n'),
    JobAssigned: [
      '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
      '👤 *JOB CARD ASSIGNED*',
      '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
      '🏢 *{{companyName}}*',
      '',
      '*JOB CARD INFORMATION*',
      '📇 Job Card: {{jobCardNo}}',
      '📊 Status: {{currentStatus}}',
      '',
      '*MAINTENANCE DETAILS*',
      '🏭 Section: {{section}}',
      '🏗️ Department: {{department}}',
      '⚙️ Machine: {{machine}}',
      '🔢 Machine Number: {{machineNumber}}',
      '📌 Machine ID: {{machineId}}',
      '🔖 Asset ID: {{assetId}}',
      '🏷️ Category: {{category}}',
      '⚠️ *Issue:* {{issue}}',
      '🎯 Priority: {{priority}}',
      '',
      '*RESPONSIBILITY*',
      '🛠️ Maintenance Team: {{maintenanceTeam}}',
      '👤 Assigned To: {{assignedTo}}',
      '',
      '*ACTION*',
      '👤 Job card assigned to technician',
      '',
      '*SYSTEM*',
      '💾 Created By: {{createdBy}}',
      '🔔 Notification: Job Card Assigned',
      '',
      '*NEXT ACTION*',
      '🎯 Technician to start maintenance work',
      '',
      '🤖 Generated by {{companyName}} | 🏢 Pakistan Wire Industries',
      '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━'
    ].join('\n'),
    JobStarted: [
      '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
      '▶️ *JOB CARD STARTED*',
      '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
      '🏢 *{{companyName}}*',
      '',
      '*JOB CARD INFORMATION*',
      '📇 Job Card: {{jobCardNo}}',
      '📊 Status: {{currentStatus}}',
      '▶️ Started: {{started}}',
      '',
      '*MAINTENANCE DETAILS*',
      '🏭 Section: {{section}}',
      '🏗️ Department: {{department}}',
      '⚙️ Machine: {{machine}}',
      '🔢 Machine Number: {{machineNumber}}',
      '📌 Machine ID: {{machineId}}',
      '🔖 Asset ID: {{assetId}}',
      '🏷️ Category: {{category}}',
      '⚠️ *Issue:* {{issue}}',
      '🎯 Priority: {{priority}}',
      '',
      '*RESPONSIBILITY*',
      '🛠️ Maintenance Team: {{maintenanceTeam}}',
      '👤 Assigned To: {{assignedTo}}',
      '▶️ Started By: {{startedBy}}',
      '',
      '*ACTION*',
      '▶️ Maintenance work started',
      '',
      '*SYSTEM*',
      '💾 Created By: {{createdBy}}',
      '🔔 Notification: Job Card Started',
      '',
      '*NEXT ACTION*',
      '🎯 Complete repair and submit for review',
      '',
      '🤖 Generated by {{companyName}} | 🏢 Pakistan Wire Industries',
      '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━'
    ].join('\n'),
    JobClosed: [
      '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
      '🔒 *JOB CARD CLOSED*',
      '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
      '🏢 *{{companyName}}*',
      '',
      '*JOB CARD INFORMATION*',
      '📇 Job Card: {{jobCardNo}}',
      '📊 Status: {{currentStatus}}',
      '🔒 Closed: {{closed}}',
      '',
      '*MAINTENANCE DETAILS*',
      '🏭 Section: {{section}}',
      '🏗️ Department: {{department}}',
      '⚙️ Machine: {{machine}}',
      '🔢 Machine Number: {{machineNumber}}',
      '📌 Machine ID: {{machineId}}',
      '🔖 Asset ID: {{assetId}}',
      '🏷️ Category: {{category}}',
      '⚠️ *Issue:* {{issue}}',
      '🎯 Priority: {{priority}}',
      '🔨 Breakdown Type: {{breakdownType}}',
      '🩺 Root Cause: {{rootCause}}',
      '✅ *Resolution:* {{correctiveAction}}',
      '📝 Final Remarks: {{finalRemarks}}',
      '⏱️ Working Time: {{workingTime}}',
      '📉 Downtime: {{downtime}}',
      '🕓 Total Duration: {{totalDuration}}',
      '',
      '*RESPONSIBILITY*',
      '🛠️ Maintenance Team: {{maintenanceTeam}}',
      '👤 Assigned To: {{assignedTo}}',
      '🔒 Closed By: {{closedBy}}',
      '',
      '*ACTION*',
      '🔒 Job closed after completion',
      '',
      '*SYSTEM*',
      '💾 Created By: {{createdBy}}',
      '🔔 Notification: Job Card Closed',
      '',
      '*NEXT ACTION*',
      '🎯 None - job complete',
      '',
      '🤖 Generated by {{companyName}} | 🏢 Pakistan Wire Industries',
      '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━'
    ].join('\n'),
    JobApproved: [
      '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
      '✅ *JOB CARD APPROVED*',
      '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
      '🏢 *{{companyName}}*',
      '',
      '*JOB CARD INFORMATION*',
      '📇 Job Card: {{jobCardNo}}',
      '📊 Status: {{currentStatus}}',
      '✅ Approved: {{approved}}',
      '',
      '*MAINTENANCE DETAILS*',
      '🏭 Section: {{section}}',
      '🏗️ Department: {{department}}',
      '⚙️ Machine: {{machine}}',
      '🔢 Machine Number: {{machineNumber}}',
      '📌 Machine ID: {{machineId}}',
      '🔖 Asset ID: {{assetId}}',
      '🏷️ Category: {{category}}',
      '⚠️ *Issue:* {{issue}}',
      '🎯 Priority: {{priority}}',
      '',
      '*RESPONSIBILITY*',
      '🛠️ Maintenance Team: {{maintenanceTeam}}',
      '👤 Assigned To: {{assignedTo}}',
      '✅ Approved By: {{approvedBy}}',
      '',
      '*ACTION*',
      '✅ Job approved and closed out',
      '📝 Remarks: {{approvalRemarks}}',
      '',
      '*SYSTEM*',
      '💾 Created By: {{createdBy}}',
      '🔔 Notification: Job Card Approved',
      '',
      '*NEXT ACTION*',
      '🎯 None - job complete',
      '',
      '🤖 Generated by {{companyName}} | 🏢 Pakistan Wire Industries',
      '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━'
    ].join('\n')
  },
  TEMPLATE_VARIABLES: {
    JobOpened: 'companyName,jobCardNo,currentStatus,opened,section,department,machine,machineNumber,machineId,assetId,category,issue,priority,maintenanceTeam,reportedBy,assignedTo,initialRemarks,createdBy',
    JobAssigned: 'companyName,jobCardNo,currentStatus,section,department,machine,machineNumber,machineId,assetId,category,issue,priority,maintenanceTeam,assignedTo,createdBy',
    JobStarted: 'companyName,jobCardNo,currentStatus,started,section,department,machine,machineNumber,machineId,assetId,category,issue,priority,maintenanceTeam,assignedTo,startedBy,createdBy',
    JobClosed: 'companyName,jobCardNo,currentStatus,closed,section,department,machine,machineNumber,machineId,assetId,category,issue,priority,breakdownType,rootCause,correctiveAction,finalRemarks,workingTime,downtime,totalDuration,maintenanceTeam,assignedTo,closedBy,createdBy',
    JobApproved: 'companyName,jobCardNo,currentStatus,approved,section,department,machine,machineNumber,machineId,assetId,category,issue,priority,approvalRemarks,maintenanceTeam,assignedTo,approvedBy,createdBy'
  },
  JC_TEMPLATE_IDS: ['TMP001', 'TMP002', 'TMP003', 'TMP004', 'TMP005'],
  JC_TEMPLATE_EVENTS: { TMP001: 'JobOpened', TMP002: 'JobAssigned', TMP003: 'JobStarted', TMP004: 'JobClosed', TMP005: 'JobApproved' },
  MIGRATED_KEY: 'WHATSAPP_JCE_TEMPLATES_MIGRATED'
};

function whatsappInitLogsSheet() {
  var sheet = getSheet(WHATSAPP.SHEET);
  ensureHeaders(sheet, WHATSAPP.FIELDS);
  ensureSheetColumns(sheet, WHATSAPP.FIELDS);
}

function whatsappInitTemplatesSheet() {
  var sheet = getSheet(WHATSAPP.TEMPLATES_SHEET);
  ensureHeaders(sheet, WHATSAPP.TEMPLATE_FIELDS);
  var existing = getAllData(WHATSAPP.TEMPLATES_SHEET);
  if (!existing || existing.length === 0) {
    var now = getCurrentTimestamp();
    var defaults = [
      { TemplateID: 'TMP001', TemplateName: 'Job Opened', EventType: WHATSAPP.TEMPLATES.JC_OPENED, TemplateBody: WHATSAPP_JCE.TEMPLATE_BODIES[WHATSAPP.TEMPLATES.JC_OPENED], Variables: WHATSAPP_JCE.TEMPLATE_VARIABLES[WHATSAPP.TEMPLATES.JC_OPENED], CreatedBy: 'system', CreatedAt: now },
      { TemplateID: 'TMP002', TemplateName: 'Job Assigned', EventType: WHATSAPP.TEMPLATES.JC_ASSIGNED, TemplateBody: WHATSAPP_JCE.TEMPLATE_BODIES[WHATSAPP.TEMPLATES.JC_ASSIGNED], Variables: WHATSAPP_JCE.TEMPLATE_VARIABLES[WHATSAPP.TEMPLATES.JC_ASSIGNED], CreatedBy: 'system', CreatedAt: now },
      { TemplateID: 'TMP003', TemplateName: 'Job Started', EventType: WHATSAPP.TEMPLATES.JC_STARTED, TemplateBody: WHATSAPP_JCE.TEMPLATE_BODIES[WHATSAPP.TEMPLATES.JC_STARTED], Variables: WHATSAPP_JCE.TEMPLATE_VARIABLES[WHATSAPP.TEMPLATES.JC_STARTED], CreatedBy: 'system', CreatedAt: now },
      { TemplateID: 'TMP004', TemplateName: 'Job Closed', EventType: WHATSAPP.TEMPLATES.JC_CLOSED, TemplateBody: WHATSAPP_JCE.TEMPLATE_BODIES[WHATSAPP.TEMPLATES.JC_CLOSED], Variables: WHATSAPP_JCE.TEMPLATE_VARIABLES[WHATSAPP.TEMPLATES.JC_CLOSED], CreatedBy: 'system', CreatedAt: now },
      { TemplateID: 'TMP005', TemplateName: 'Job Approved', EventType: WHATSAPP.TEMPLATES.JC_APPROVED, TemplateBody: WHATSAPP_JCE.TEMPLATE_BODIES[WHATSAPP.TEMPLATES.JC_APPROVED], Variables: WHATSAPP_JCE.TEMPLATE_VARIABLES[WHATSAPP.TEMPLATES.JC_APPROVED], CreatedBy: 'system', CreatedAt: now },
      { TemplateID: 'TMP006', TemplateName: 'PM Due Reminder', EventType: WHATSAPP.TEMPLATES.PM_DUE, TemplateBody: '*PM Due Reminder*\n\nPM: {{title}}\nMachine: {{machine}}\nAssigned To: {{assignedTech}}\nDue Date: {{dueDate}}\nFrequency: {{frequency}}', Variables: 'title,machine,assignedTech,dueDate,frequency', CreatedBy: 'system', CreatedAt: now },
      { TemplateID: 'TMP007', TemplateName: 'PM Overdue', EventType: WHATSAPP.TEMPLATES.PM_OVERDUE, TemplateBody: '*PM Overdue Alert*\n\nPM: {{title}}\nMachine: {{machine}}\nOverdue Since: {{dueDate}}\nFrequency: {{frequency}}', Variables: 'title,machine,dueDate,frequency', CreatedBy: 'system', CreatedAt: now },
      { TemplateID: 'TMP008', TemplateName: 'Low Stock Alert', EventType: WHATSAPP.TEMPLATES.LOW_STOCK, TemplateBody: '*Low Stock Alert*\n\nPart: {{partName}} ({{partCode}})\nCurrent Stock: {{currentStock}} {{unit}}\nMinimum Stock: {{minStock}} {{unit}}\nReorder Level: {{reorderLevel}} {{unit}}\nLocation: {{storeLocation}}', Variables: 'partCode,partName,currentStock,minStock,reorderLevel,unit,storeLocation', CreatedBy: 'system', CreatedAt: now },
      { TemplateID: 'TMP009', TemplateName: 'Out of Stock Alert', EventType: WHATSAPP.TEMPLATES.OUT_OF_STOCK, TemplateBody: '*Out of Stock Alert*\n\nPart: {{partName}} ({{partCode}})\nStock: 0 {{unit}}\nAction Required Immediately!', Variables: 'partCode,partName,unit', CreatedBy: 'system', CreatedAt: now },
      { TemplateID: 'TMP010', TemplateName: 'Purchase Request', EventType: WHATSAPP.TEMPLATES.PURCHASE_REQUEST, TemplateBody: '*Purchase Request*\n\nPart: {{partName}} ({{partCode}})\nQuantity: {{quantity}} {{unit}}\nRequested By: {{requestedBy}}\nRemarks: {{remarks}}', Variables: 'partCode,partName,quantity,unit,requestedBy,remarks', CreatedBy: 'system', CreatedAt: now },
      { TemplateID: 'TMP011', TemplateName: 'Goods Received', EventType: WHATSAPP.TEMPLATES.GOODS_RECEIPT, TemplateBody: '*Goods Received*\n\nGRN: {{grnNo}}\nPart: {{partName}} ({{partCode}})\nQuantity: {{quantity}}\nSupplier: {{supplier}}\nInvoice: {{invoiceNo}}\nReceived By: {{receivedBy}}', Variables: 'grnNo,partCode,partName,quantity,supplier,invoiceNo,receivedBy', CreatedBy: 'system', CreatedAt: now },
      { TemplateID: 'TMP012', TemplateName: 'User Created', EventType: WHATSAPP.TEMPLATES.USER_CREATED, TemplateBody: '*User Account Created*\n\nName: {{name}}\nEmail: {{email}}\nRole: {{role}}\nDepartment: {{department}}\nDesignation: {{designation}}\nTemporary Password: {{tempPassword}}', Variables: 'name,email,role,department,designation,tempPassword', CreatedBy: 'system', CreatedAt: now },
      { TemplateID: 'TMP013', TemplateName: 'Password Reset', EventType: WHATSAPP.TEMPLATES.PASSWORD_RESET, TemplateBody: '*Password Reset*\n\nUser: {{name}} ({{email}})\nNew Temporary Password: {{tempPassword}}\nPlease change on next login.', Variables: 'name,email,tempPassword', CreatedBy: 'system', CreatedAt: now }
    ];
    defaults.forEach(function(t) { addRow(WHATSAPP.TEMPLATES_SHEET, t); });
  }
}

function whatsappEnsureDefaults() {
  if (getSetting(WHATSAPP.SETTINGS.ENABLED) === null) saveSetting(WHATSAPP.SETTINGS.ENABLED, 'false');
  if (getSetting(WHATSAPP.SETTINGS.COMPANY_NAME) === null) saveSetting(WHATSAPP.SETTINGS.COMPANY_NAME, WHATSAPP.DEFAULTS.COMPANY_NAME);
  if (getSetting(WHATSAPP.SETTINGS.DEFAULT_COUNTRY_CODE) === null) saveSetting(WHATSAPP.SETTINGS.DEFAULT_COUNTRY_CODE, WHATSAPP.DEFAULTS.DEFAULT_COUNTRY_CODE);
  if (getSetting(WHATSAPP.SETTINGS.PROVIDER) === null) saveSetting(WHATSAPP.SETTINGS.PROVIDER, WHATSAPP.DEFAULTS.PROVIDER);
  if (getSetting(WHATSAPP.SETTINGS.API_ENDPOINT) === null) saveSetting(WHATSAPP.SETTINGS.API_ENDPOINT, WHATSAPP.DEFAULTS.API_ENDPOINT);
  if (getSetting(WHATSAPP.SETTINGS.API_TOKEN) === null) saveSetting(WHATSAPP.SETTINGS.API_TOKEN, '');
  if (getSetting(WHATSAPP.SETTINGS.PHONE_NUMBER_ID) === null) saveSetting(WHATSAPP.SETTINGS.PHONE_NUMBER_ID, '');
  if (getSetting(WHATSAPP.SETTINGS.BUSINESS_ACCOUNT_ID) === null) saveSetting(WHATSAPP.SETTINGS.BUSINESS_ACCOUNT_ID, '');
  if (getSetting(WHATSAPP.SETTINGS.TEST_PHONE) === null) saveSetting(WHATSAPP.SETTINGS.TEST_PHONE, '');
  if (getSetting(WHATSAPP.SETTINGS.TEST_MESSAGE) === null) saveSetting(WHATSAPP.SETTINGS.TEST_MESSAGE, WHATSAPP.DEFAULTS.TEST_MESSAGE);
  whatsappEnsureProviderDefaults();
}

function whatsappEnsureProviderDefaults() {
  var provider = getSetting(WHATSAPP.SETTINGS.PROVIDER) || WHATSAPP.DEFAULTS.PROVIDER;
  var endpoint = getSetting(WHATSAPP.SETTINGS.API_ENDPOINT) || '';
  var sharedLooksMeta = provider === 'meta' || endpoint.indexOf('graph.facebook.com') !== -1;
  var sharedLooksTwilio = provider === 'twilio' || endpoint.indexOf('api.twilio.com') !== -1;
  if (getSetting(WHATSAPP.SETTINGS.META_API_ENDPOINT) === null) {
    saveSetting(WHATSAPP.SETTINGS.META_API_ENDPOINT, sharedLooksMeta ? (endpoint || WHATSAPP.DEFAULTS.API_ENDPOINT) : WHATSAPP.DEFAULTS.API_ENDPOINT);
  }
  if (getSetting(WHATSAPP.SETTINGS.META_API_TOKEN) === null) {
    saveSetting(WHATSAPP.SETTINGS.META_API_TOKEN, sharedLooksMeta ? (getSetting(WHATSAPP.SETTINGS.API_TOKEN) || '') : '');
  }
  if (getSetting(WHATSAPP.SETTINGS.META_PHONE_NUMBER_ID) === null) {
    saveSetting(WHATSAPP.SETTINGS.META_PHONE_NUMBER_ID, sharedLooksMeta ? (getSetting(WHATSAPP.SETTINGS.PHONE_NUMBER_ID) || '') : '');
  }
  if (getSetting(WHATSAPP.SETTINGS.META_BUSINESS_ACCOUNT_ID) === null) {
    saveSetting(WHATSAPP.SETTINGS.META_BUSINESS_ACCOUNT_ID, sharedLooksMeta ? (getSetting(WHATSAPP.SETTINGS.BUSINESS_ACCOUNT_ID) || '') : '');
  }
  if (getSetting(WHATSAPP.SETTINGS.TWILIO_API_ENDPOINT) === null) {
    saveSetting(WHATSAPP.SETTINGS.TWILIO_API_ENDPOINT, sharedLooksTwilio ? (endpoint || WHATSAPP.TWILIO_DEFAULTS.API_ENDPOINT) : WHATSAPP.TWILIO_DEFAULTS.API_ENDPOINT);
  }
  if (getSetting(WHATSAPP.SETTINGS.TWILIO_API_TOKEN) === null) {
    saveSetting(WHATSAPP.SETTINGS.TWILIO_API_TOKEN, sharedLooksTwilio ? (getSetting(WHATSAPP.SETTINGS.API_TOKEN) || '') : '');
  }
  if (getSetting(WHATSAPP.SETTINGS.TWILIO_PHONE_NUMBER_ID) === null) {
    saveSetting(WHATSAPP.SETTINGS.TWILIO_PHONE_NUMBER_ID, sharedLooksTwilio ? (getSetting(WHATSAPP.SETTINGS.PHONE_NUMBER_ID) || '') : '');
  }
  if (getSetting(WHATSAPP.SETTINGS.TWILIO_BUSINESS_ACCOUNT_ID) === null) {
    saveSetting(WHATSAPP.SETTINGS.TWILIO_BUSINESS_ACCOUNT_ID, sharedLooksTwilio ? (getSetting(WHATSAPP.SETTINGS.BUSINESS_ACCOUNT_ID) || '') : '');
  }
  if (getSetting(WHATSAPP.SETTINGS.ULTRAMSG_API_URL) === null) saveSetting(WHATSAPP.SETTINGS.ULTRAMSG_API_URL, WHATSAPP.ULTRAMSG_DEFAULTS.API_URL);
  if (getSetting(WHATSAPP.SETTINGS.ULTRAMSG_INSTANCE_ID) === null) saveSetting(WHATSAPP.SETTINGS.ULTRAMSG_INSTANCE_ID, '');
  if (getSetting(WHATSAPP.SETTINGS.ULTRAMSG_TOKEN) === null) saveSetting(WHATSAPP.SETTINGS.ULTRAMSG_TOKEN, '');
}

function whatsappCleanSetting(v, fallback) {
  if (v === 'undefined' || v === null) return fallback;
  return v || fallback;
}

function whatsappGetSettings() {
  try {
    whatsappEnsureDefaults();
    var provider = getSetting(WHATSAPP.SETTINGS.PROVIDER) || WHATSAPP.DEFAULTS.PROVIDER;
    var meta = {
      apiEndpoint: whatsappCleanSetting(getSetting(WHATSAPP.SETTINGS.META_API_ENDPOINT), WHATSAPP.DEFAULTS.API_ENDPOINT),
      apiToken: whatsappCleanSetting(getSetting(WHATSAPP.SETTINGS.META_API_TOKEN), ''),
      phoneNumberId: whatsappCleanSetting(getSetting(WHATSAPP.SETTINGS.META_PHONE_NUMBER_ID), ''),
      businessAccountId: whatsappCleanSetting(getSetting(WHATSAPP.SETTINGS.META_BUSINESS_ACCOUNT_ID), '')
    };
    var twilio = {
      apiEndpoint: whatsappCleanSetting(getSetting(WHATSAPP.SETTINGS.TWILIO_API_ENDPOINT), WHATSAPP.TWILIO_DEFAULTS.API_ENDPOINT),
      apiToken: whatsappCleanSetting(getSetting(WHATSAPP.SETTINGS.TWILIO_API_TOKEN), ''),
      phoneNumberId: whatsappCleanSetting(getSetting(WHATSAPP.SETTINGS.TWILIO_PHONE_NUMBER_ID), ''),
      businessAccountId: whatsappCleanSetting(getSetting(WHATSAPP.SETTINGS.TWILIO_BUSINESS_ACCOUNT_ID), '')
    };
    var ultramsg = {
      apiUrl: whatsappCleanSetting(getSetting(WHATSAPP.SETTINGS.ULTRAMSG_API_URL), WHATSAPP.ULTRAMSG_DEFAULTS.API_URL),
      instanceId: whatsappCleanSetting(getSetting(WHATSAPP.SETTINGS.ULTRAMSG_INSTANCE_ID), ''),
      token: whatsappCleanSetting(getSetting(WHATSAPP.SETTINGS.ULTRAMSG_TOKEN), '')
    };
    var active = provider === 'twilio' ? twilio : (provider === 'ultramsg' ? ultramsg : meta);
    return {
      enabled: getSetting(WHATSAPP.SETTINGS.ENABLED) === true || getSetting(WHATSAPP.SETTINGS.ENABLED) === 'true',
      companyName: getSetting(WHATSAPP.SETTINGS.COMPANY_NAME) || WHATSAPP.DEFAULTS.COMPANY_NAME,
      defaultCountryCode: getSetting(WHATSAPP.SETTINGS.DEFAULT_COUNTRY_CODE) || WHATSAPP.DEFAULTS.DEFAULT_COUNTRY_CODE,
      provider: provider,
      apiEndpoint: active.apiUrl || active.apiEndpoint || '',
      apiToken: active.token || active.apiToken || '',
      instanceId: active.instanceId || '',
      phoneNumberId: active.phoneNumberId || '',
      businessAccountId: active.businessAccountId || '',
      testPhone: getSetting(WHATSAPP.SETTINGS.TEST_PHONE) || '',
      testMessage: getSetting(WHATSAPP.SETTINGS.TEST_MESSAGE) || WHATSAPP.DEFAULTS.TEST_MESSAGE,
      meta: meta,
      twilio: twilio,
      ultramsg: ultramsg
    };
  } catch (e) {
    return { enabled: false, provider: WHATSAPP.DEFAULTS.PROVIDER, companyName: WHATSAPP.DEFAULTS.COMPANY_NAME, defaultCountryCode: WHATSAPP.DEFAULTS.DEFAULT_COUNTRY_CODE };
  }
}

function whatsappSaveSettings(data) {
  try {
    requireUserPermission('CanManageWhatsApp', data);
    whatsappEnsureDefaults();
    if (data.hasOwnProperty('enabled')) saveSetting(WHATSAPP.SETTINGS.ENABLED, data.enabled ? 'true' : 'false');
    if (data.hasOwnProperty('companyName')) saveSetting(WHATSAPP.SETTINGS.COMPANY_NAME, String(data.companyName));
    if (data.hasOwnProperty('defaultCountryCode')) saveSetting(WHATSAPP.SETTINGS.DEFAULT_COUNTRY_CODE, String(data.defaultCountryCode));
    if (data.hasOwnProperty('provider')) saveSetting(WHATSAPP.SETTINGS.PROVIDER, String(data.provider));
    if (data.hasOwnProperty('apiEndpoint')) saveSetting(WHATSAPP.SETTINGS.API_ENDPOINT, String(data.apiEndpoint));
    if (data.hasOwnProperty('apiToken')) saveSetting(WHATSAPP.SETTINGS.API_TOKEN, String(data.apiToken));
    if (data.hasOwnProperty('phoneNumberId')) saveSetting(WHATSAPP.SETTINGS.PHONE_NUMBER_ID, String(data.phoneNumberId));
    if (data.hasOwnProperty('businessAccountId')) saveSetting(WHATSAPP.SETTINGS.BUSINESS_ACCOUNT_ID, String(data.businessAccountId));
    if (data.hasOwnProperty('testPhone')) saveSetting(WHATSAPP.SETTINGS.TEST_PHONE, String(data.testPhone));
    if (data.hasOwnProperty('testMessage')) saveSetting(WHATSAPP.SETTINGS.TEST_MESSAGE, String(data.testMessage));
    whatsappSaveProviderConfigs(data);
    var safeData = JSON.parse(JSON.stringify(data));
    if (safeData && safeData.apiToken) safeData.apiToken = '***';
    if (safeData && safeData.meta && safeData.meta.apiToken) safeData.meta.apiToken = '***';
    if (safeData && safeData.twilio && safeData.twilio.apiToken) safeData.twilio.apiToken = '***';
    if (safeData && safeData.ultramsg && safeData.ultramsg.token) safeData.ultramsg.token = '***';
    logActivity('WhatsApp Settings Updated', JSON.stringify(safeData));
    try { createAuditLog(CONFIG.AUDIT_MODULES.SETTINGS, CONFIG.AUDIT_ACTIONS.UPDATE, 'WhatsAppSettings', 'WhatsApp settings changed', '', JSON.stringify(safeData).substring(0, 200), 'Success', 'WhatsApp settings updated'); } catch(e) {}
    return { success: true, settings: whatsappGetSettings() };
  } catch (e) {
    return { success: false, message: e.message };
  }
}

function whatsappSaveProviderConfigs(data) {
  var hasFields = data.hasOwnProperty('apiEndpoint') || data.hasOwnProperty('apiToken') ||
                  data.hasOwnProperty('phoneNumberId') || data.hasOwnProperty('businessAccountId') ||
                  data.hasOwnProperty('instanceId') || data.hasOwnProperty('ultramsg');
  if (!hasFields) return;
  var provider = data.hasOwnProperty('provider') ? String(data.provider) : (getSetting(WHATSAPP.SETTINGS.PROVIDER) || WHATSAPP.DEFAULTS.PROVIDER);
  var metaCfg = data.meta || null;
  var twilioCfg = data.twilio || null;
  var ultramsgCfg = data.ultramsg || null;
  if (provider === 'meta' && !metaCfg) {
    metaCfg = {};
    if (data.hasOwnProperty('apiEndpoint') && data.apiEndpoint !== undefined) metaCfg.apiEndpoint = data.apiEndpoint;
    if (data.hasOwnProperty('apiToken') && data.apiToken !== undefined) metaCfg.apiToken = data.apiToken;
    if (data.hasOwnProperty('phoneNumberId') && data.phoneNumberId !== undefined) metaCfg.phoneNumberId = data.phoneNumberId;
    if (data.hasOwnProperty('businessAccountId') && data.businessAccountId !== undefined) metaCfg.businessAccountId = data.businessAccountId;
  }
  if (provider === 'twilio' && !twilioCfg) {
    twilioCfg = {};
    if (data.hasOwnProperty('apiEndpoint') && data.apiEndpoint !== undefined) twilioCfg.apiEndpoint = data.apiEndpoint;
    if (data.hasOwnProperty('apiToken') && data.apiToken !== undefined) twilioCfg.apiToken = data.apiToken;
    if (data.hasOwnProperty('phoneNumberId') && data.phoneNumberId !== undefined) twilioCfg.phoneNumberId = data.phoneNumberId;
    if (data.hasOwnProperty('businessAccountId') && data.businessAccountId !== undefined) twilioCfg.businessAccountId = data.businessAccountId;
  }
  if (provider === 'ultramsg' && !ultramsgCfg) {
    ultramsgCfg = {};
    if (data.hasOwnProperty('apiEndpoint') && data.apiEndpoint !== undefined) ultramsgCfg.apiUrl = data.apiEndpoint;
    if (data.hasOwnProperty('apiToken') && data.apiToken !== undefined) ultramsgCfg.token = data.apiToken;
    if (data.hasOwnProperty('instanceId') && data.instanceId !== undefined) ultramsgCfg.instanceId = data.instanceId;
  }
  if (metaCfg) {
    if (metaCfg.hasOwnProperty('apiEndpoint') && metaCfg.apiEndpoint !== undefined) saveSetting(WHATSAPP.SETTINGS.META_API_ENDPOINT, String(metaCfg.apiEndpoint));
    if (metaCfg.hasOwnProperty('apiToken') && metaCfg.apiToken !== undefined) saveSetting(WHATSAPP.SETTINGS.META_API_TOKEN, String(metaCfg.apiToken));
    if (metaCfg.hasOwnProperty('phoneNumberId') && metaCfg.phoneNumberId !== undefined) saveSetting(WHATSAPP.SETTINGS.META_PHONE_NUMBER_ID, String(metaCfg.phoneNumberId));
    if (metaCfg.hasOwnProperty('businessAccountId') && metaCfg.businessAccountId !== undefined) saveSetting(WHATSAPP.SETTINGS.META_BUSINESS_ACCOUNT_ID, String(metaCfg.businessAccountId));
  }
  if (twilioCfg) {
    if (twilioCfg.hasOwnProperty('apiEndpoint') && twilioCfg.apiEndpoint !== undefined) saveSetting(WHATSAPP.SETTINGS.TWILIO_API_ENDPOINT, String(twilioCfg.apiEndpoint));
    if (twilioCfg.hasOwnProperty('apiToken') && twilioCfg.apiToken !== undefined) saveSetting(WHATSAPP.SETTINGS.TWILIO_API_TOKEN, String(twilioCfg.apiToken));
    if (twilioCfg.hasOwnProperty('phoneNumberId') && twilioCfg.phoneNumberId !== undefined) saveSetting(WHATSAPP.SETTINGS.TWILIO_PHONE_NUMBER_ID, String(twilioCfg.phoneNumberId));
    if (twilioCfg.hasOwnProperty('businessAccountId') && twilioCfg.businessAccountId !== undefined) saveSetting(WHATSAPP.SETTINGS.TWILIO_BUSINESS_ACCOUNT_ID, String(twilioCfg.businessAccountId));
  }
  if (ultramsgCfg) {
    if (ultramsgCfg.hasOwnProperty('apiUrl') && ultramsgCfg.apiUrl !== undefined) saveSetting(WHATSAPP.SETTINGS.ULTRAMSG_API_URL, String(ultramsgCfg.apiUrl));
    if (ultramsgCfg.hasOwnProperty('instanceId') && ultramsgCfg.instanceId !== undefined) saveSetting(WHATSAPP.SETTINGS.ULTRAMSG_INSTANCE_ID, String(ultramsgCfg.instanceId));
    if (ultramsgCfg.hasOwnProperty('token') && ultramsgCfg.token !== undefined) saveSetting(WHATSAPP.SETTINGS.ULTRAMSG_TOKEN, String(ultramsgCfg.token));
  }
}

function whatsappFindTemplate(filter) {
  var all = getAllData(WHATSAPP.TEMPLATES_SHEET) || [];
  for (var i = 0; i < all.length; i++) {
    var ok = true;
    for (var k in filter) {
      if (String(all[i][k] === undefined ? '' : all[i][k]) !== String(filter[k])) { ok = false; break; }
    }
    if (ok) return all[i];
  }
  return null;
}

function whatsappUpgradeJceTemplates() {
  try {
    if (getSetting(WHATSAPP_JCE.MIGRATED_KEY) === true) return;
    var now = getCurrentTimestamp();
    var ids = WHATSAPP_JCE.JC_TEMPLATE_IDS || [];
    for (var i = 0; i < ids.length; i++) {
      var id = ids[i];
      var evType = WHATSAPP_JCE.JC_TEMPLATE_EVENTS[id];
      var body = WHATSAPP_JCE.TEMPLATE_BODIES[evType];
      var vars = WHATSAPP_JCE.TEMPLATE_VARIABLES[evType];
      if (!body) continue;
      var existing = whatsappFindTemplate({ TemplateID: id });
      if (!existing) continue;
      if (String(existing.TemplateBody || '').indexOf(WHATSAPP_JCE.SEP) === 0) continue;
      updateRow(WHATSAPP.TEMPLATES_SHEET, 'TemplateID', id, {
        TemplateID: id,
        TemplateBody: body,
        Variables: vars,
        UpdatedBy: 'system',
        UpdatedAt: now
      });
    }
    saveSetting(WHATSAPP_JCE.MIGRATED_KEY, 'true');
  } catch (e) {}
}

function whatsappGetTemplates() {
  try {
    whatsappUpgradeJceTemplates();
    var all = getAllData(WHATSAPP.TEMPLATES_SHEET) || [];
    all.sort(function(a, b) { return String(a.TemplateName || '').localeCompare(String(b.TemplateName || '')); });
    return all;
  } catch (e) { return []; }
}

function whatsappSaveTemplate(data) {
  try {
    var user = requireUserPermission('CanManageWhatsApp', data);
    var currentUser = (data && data._userEmail) || (user && user.Email) || '';
    if (!data || !data.TemplateBody) return { success: false, message: 'TemplateBody is required' };

    var updates = {
      TemplateID: data.TemplateID,
      TemplateBody: String(data.TemplateBody),
      UpdatedBy: currentUser || '',
      UpdatedAt: getCurrentTimestamp()
    };
    if (data.TemplateName !== undefined && data.TemplateName !== null && data.TemplateName !== '') updates.TemplateName = String(data.TemplateName);
    if (data.EventType !== undefined && data.EventType !== null && data.EventType !== '') updates.EventType = String(data.EventType);
    if (data.Variables !== undefined && data.Variables !== null) updates.Variables = String(data.Variables);

    var keys = Object.keys(updates);
    for (var i = 0; i < keys.length; i++) {
      var v = updates[keys[i]];
      if (v === undefined || v === null || v === 'undefined' || v === 'null') {
        if (keys[i] === 'TemplateBody') return { success: false, message: 'TemplateBody is required' };
        delete updates[keys[i]];
      }
    }

    var existing = null;
    if (updates.TemplateID) existing = whatsappFindTemplate({ TemplateID: updates.TemplateID });
    if (!existing && updates.EventType) existing = whatsappFindTemplate({ EventType: updates.EventType });

    if (existing) {
      updates.TemplateID = existing.TemplateID;
      updateRow(WHATSAPP.TEMPLATES_SHEET, 'TemplateID', existing.TemplateID, updates);
    } else {
      var tpl = {
        TemplateID: data.TemplateID || ('TMP' + String(Date.now()).slice(-6)),
        TemplateBody: updates.TemplateBody,
        CreatedBy: currentUser || 'system',
        CreatedAt: getCurrentTimestamp(),
        UpdatedBy: currentUser || '',
        UpdatedAt: getCurrentTimestamp()
      };
      if (data.TemplateName !== undefined && data.TemplateName !== null) tpl.TemplateName = String(data.TemplateName);
      if (data.EventType !== undefined && data.EventType !== null) tpl.EventType = String(data.EventType);
      if (data.Variables !== undefined && data.Variables !== null) tpl.Variables = String(data.Variables);
      addRow(WHATSAPP.TEMPLATES_SHEET, tpl);
    }
    return { success: true, templates: whatsappGetTemplates() };
  } catch (e) {
    return { success: false, message: e.message };
  }
}

function whatsappFormatMessage(templateBody, variables) {
  var msg = templateBody || '';
  for (var key in variables) {
    var regex = new RegExp('\\{\\{' + key + '\\}\\}', 'g');
    msg = msg.replace(regex, String(variables[key] || ''));
  }
  msg = msg.replace(/\{\{\w+\}\}/g, '');
  return msg;
}

function whatsappLog(messageId, recipient, phoneNumber, module, refId, template, status, provider, errorMsg, sentBy, idempotencyKey) {
  try {
    whatsappInitLogsSheet();
    var maxNum = 0;
    var existing = getAllData(WHATSAPP.SHEET) || [];
    existing.forEach(function(r) {
      var mid = String(r.MessageID || '');
      var num = parseInt(mid.replace('WA', ''), 10);
      if (!isNaN(num) && num > maxNum) maxNum = num;
    });
    var waId = 'WA' + String(maxNum + 1).padStart(5, '0');
    var row = {};
    WHATSAPP.FIELDS.forEach(function(f, idx) {
      if (idx === 0) row[f] = waId;
      else if (f === 'DateTime') row[f] = getCurrentTimestamp();
      else if (f === 'Recipient') row[f] = recipient || '';
      else if (f === 'PhoneNumber') row[f] = phoneNumber || '';
      else if (f === 'Module') row[f] = module || '';
      else if (f === 'ReferenceID') row[f] = refId || '';
      else if (f === 'Template') row[f] = template || '';
      else if (f === 'Status') row[f] = status || WHATSAPP.STATUS.PENDING;
      else if (f === 'Provider') row[f] = provider || '';
      else if (f === 'ErrorMessage') row[f] = errorMsg || '';
      else if (f === 'SentBy') row[f] = sentBy || '';
      else if (f === 'IdempotencyKey') row[f] = idempotencyKey || '';
      else row[f] = '';
    });
    addRow(WHATSAPP.SHEET, row);
    return waId;
  } catch (e) { return ''; }
}

function whatsappGetLogs(filters) {
  try {
    var allLogs = getAllData(WHATSAPP.SHEET) || [];
    var limit = (filters && filters.limit) ? parseInt(filters.limit, 10) : 0;
    allLogs.sort(function(a, b) { return String(b.DateTime || '').localeCompare(String(a.DateTime || '')); });
    if (filters && (filters.module || filters.status || filters.recipient)) {
      allLogs = allLogs.filter(function(log) {
        if (filters.module && log.Module !== filters.module) return false;
        if (filters.status && log.Status !== filters.status) return false;
        if (filters.recipient && log.Recipient !== filters.recipient) return false;
        return true;
      });
    }
    if (limit > 0 && allLogs.length > limit) allLogs = allLogs.slice(0, limit);
    return allLogs;
  } catch (e) { return []; }
}

function whatsappGetDashboardStats() {
  try {
    var logs = getAllData(WHATSAPP.SHEET) || [];
    var today = new Date();
    var todayStr = today.toISOString().substring(0, 10);
    var sentToday = 0, failedToday = 0, pendingToday = 0;
    logs.forEach(function(log) {
      var logDate = String(log.DateTime || '').substring(0, 10);
      if (logDate === todayStr) {
        if (log.Status === WHATSAPP.STATUS.SENT) sentToday++;
        else if (log.Status === WHATSAPP.STATUS.FAILED) failedToday++;
        else if (log.Status === WHATSAPP.STATUS.PENDING) pendingToday++;
      }
    });
    return { sentToday: sentToday, failedToday: failedToday, pendingToday: pendingToday };
  } catch (e) { return { sentToday: 0, failedToday: 0, pendingToday: 0 }; }
}

function whatsappGetPanelData() {
  try {
    var stats = whatsappGetDashboardStats();
    var recent = whatsappGetLogs({ limit: 10 });
    return { stats: stats, recentLogs: recent };
  } catch (e) { return { stats: { sentToday: 0, failedToday: 0, pendingToday: 0 }, recentLogs: [] }; }
}

function whatsappProviderSend(settings, phoneNumber, messageBody) {
  var provider = settings.provider || WHATSAPP.DEFAULTS.PROVIDER;
  if (provider === 'meta') return whatsappMetaSend(settings, phoneNumber, messageBody);
  if (provider === 'twilio') return whatsappTwilioSend(settings, phoneNumber, messageBody);
  if (provider === 'ultramsg') return whatsappUltraMsgSend(settings, phoneNumber, messageBody);
  return { success: false, message: 'Unknown provider: ' + provider };
}

function whatsappMetaSend(settings, phoneNumber, messageBody) {
  try {
    var token = settings.apiToken;
    var phoneNumberId = settings.phoneNumberId;
    var apiEndpoint = settings.apiEndpoint || WHATSAPP.DEFAULTS.API_ENDPOINT;
    if (!token || !phoneNumberId) return { success: false, message: 'Meta API credentials not configured' };
    var url = apiEndpoint.replace(/\/+$/, '') + '/' + phoneNumberId + '/messages';
    var payload = {
      messaging_product: 'whatsapp',
      to: phoneNumber,
      type: 'text',
      text: { body: messageBody }
    };
    var options = {
      method: 'post',
      contentType: 'application/json',
      headers: { Authorization: 'Bearer ' + token },
      payload: JSON.stringify(payload),
      muteHttpExceptions: true
    };
    var response = UrlFetchApp.fetch(url, options);
    var code = response.getResponseCode();
    var body = JSON.parse(response.getContentText());
    if (code >= 200 && code < 300) {
      var msgId = body.messages && body.messages[0] ? body.messages[0].id : '';
      return { success: true, messageId: msgId, message: 'Sent via Meta API' };
    }
    return { success: false, message: 'Meta API error (' + code + '): ' + (body.error ? body.error.message : JSON.stringify(body)) };
  } catch (e) {
    return { success: false, message: 'Meta API exception: ' + e.message };
  }
}

function whatsappTwilioSend(settings, phoneNumber, messageBody) {
  try {
    var token = settings.apiToken;
    var apiEndpoint = settings.apiEndpoint || 'https://api.twilio.com/2010-04-01';
    if (!token || !apiEndpoint) return { success: false, message: 'Twilio credentials not configured' };
    var accountSid = settings.businessAccountId;
    if (!accountSid) return { success: false, message: 'Twilio Account SID not configured' };
    var url = apiEndpoint.replace(/\/+$/, '') + '/Accounts/' + accountSid + '/Messages.json';
    var fromNumber = settings.phoneNumberId;
    var payload = {
      To: 'whatsapp:' + phoneNumber,
      From: fromNumber ? 'whatsapp:' + fromNumber : '',
      Body: messageBody
    };
    var auth = Utilities.base64Encode(accountSid + ':' + token);
    var options = {
      method: 'post',
      contentType: 'application/x-www-form-urlencoded',
      headers: { Authorization: 'Basic ' + auth },
      payload: payload,
      muteHttpExceptions: true
    };
    var response = UrlFetchApp.fetch(url, options);
    var code = response.getResponseCode();
    var body = JSON.parse(response.getContentText());
    if (code >= 200 && code < 300) {
      return { success: true, messageId: body.sid || '', message: 'Sent via Twilio' };
    }
    return { success: false, message: 'Twilio API error (' + code + '): ' + (body.message || JSON.stringify(body)) };
  } catch (e) {
    return { success: false, message: 'Twilio API exception: ' + e.message };
  }
}

function whatsappUltraMsgSend(settings, phoneNumber, messageBody) {
  try {
    var apiUrl = (settings.ultramsg && settings.ultramsg.apiUrl) || settings.apiEndpoint || WHATSAPP.ULTRAMSG_DEFAULTS.API_URL;
    var instanceId = (settings.ultramsg && settings.ultramsg.instanceId) || settings.instanceId || '';
    var token = (settings.ultramsg && settings.ultramsg.token) || settings.apiToken || '';
    if (!instanceId || !token) return { success: false, message: 'UltraMsg credentials not configured' };
    var url = apiUrl.replace(/\/+$/, '') + '/' + encodeURIComponent(instanceId) + '/messages/chat';
    var payload = {
      token: token,
      to: phoneNumber,
      body: messageBody
    };
    var options = {
      method: 'post',
      contentType: 'application/json',
      payload: JSON.stringify(payload),
      muteHttpExceptions: true
    };
    var response = UrlFetchApp.fetch(url, options);
    var code = response.getResponseCode();
    var body;
    try { body = JSON.parse(response.getContentText()); } catch (e) { body = {}; }
    var failed = body.sent === false || body.sent === 'false' || !!body.error;
    if (code >= 200 && code < 300 && !failed) {
      return { success: true, messageId: body.messageId || body.id || '', message: 'Sent via UltraMsg API' };
    }
    var errText = body.description || body.message || body.error || JSON.stringify(body);
    return { success: false, message: 'UltraMsg API error (' + code + '): ' + errText };
  } catch (e) {
    return { success: false, message: 'UltraMsg API exception: ' + e.message };
  }
}

function whatsappConnectionTest(data) {
  try {
    requireUserPermission('CanManageWhatsApp', data);
    var settings = whatsappGetSettings();
    if (!settings.enabled) return { success: false, status: 'DISABLED', message: 'WhatsApp is disabled. Enable it in the integration status first.' };
    var issue = whatsappConfigIssue(settings);
    if (issue) return { success: false, status: 'CONFIGURATION_REQUIRED', message: issue };
    if (settings.provider === 'ultramsg') return whatsappUltraMsgConnectionTest(settings);
    return { success: true, status: 'CONFIGURED', message: 'Configuration looks complete. Use "Send Test" to verify message delivery.' };
  } catch (e) {
    return { success: false, status: 'PROVIDER_ERROR', message: e.message };
  }
}

function whatsappUltraMsgConnectionTest(settings) {
  try {
    var apiUrl = (settings.ultramsg && settings.ultramsg.apiUrl) || settings.apiEndpoint || WHATSAPP.ULTRAMSG_DEFAULTS.API_URL;
    var instanceId = (settings.ultramsg && settings.ultramsg.instanceId) || settings.instanceId || '';
    var token = (settings.ultramsg && settings.ultramsg.token) || settings.apiToken || '';
    if (!instanceId || !token) return { success: false, status: 'CONFIGURATION_REQUIRED', message: 'UltraMsg Instance ID and Token are required.' };
    var url = apiUrl.replace(/\/+$/, '') + '/' + encodeURIComponent(instanceId) + '/instance/me?token=' + encodeURIComponent(token);
    var options = { method: 'get', muteHttpExceptions: true };
    var response = UrlFetchApp.fetch(url, options);
    var code = response.getResponseCode();
    var body;
    try { body = JSON.parse(response.getContentText()); } catch (e) { body = {}; }
    if (code === 401 || code === 403) {
      return { success: false, status: 'AUTHORIZATION_FAILED', message: 'UltraMsg authorization failed. Check your Instance ID and Token.' };
    }
    var errText = String(body.error || body.message || '').toLowerCase();
    if (errText.indexOf('authorization') > -1 || errText.indexOf('unauthorized') > -1 || errText.indexOf('not found') > -1) {
      return { success: false, status: 'AUTHORIZATION_FAILED', message: 'UltraMsg authorization failed. Check your Instance ID and Token.' };
    }
    if (code >= 200 && code < 300 && !body.error) {
      return { success: true, status: 'CONNECTED', message: 'UltraMsg connection verified.' };
    }
    return { success: false, status: 'PROVIDER_ERROR', message: 'UltraMsg returned HTTP ' + code + (body.error ? ': ' + body.error : '') + '.' };
  } catch (e) {
    return { success: false, status: 'PROVIDER_ERROR', message: 'UltraMsg connection exception: ' + e.message };
  }
}

function whatsappSendMessage(phoneNumber, messageBody, module, refId, templateName, recipientName, sentBy, idempotencyKey) {
  try {
    var settings = whatsappGetSettings();
    if (!settings.enabled) return { success: false, status: WHATSAPP.STATUS.PENDING, message: 'WhatsApp disabled' };
    if (!phoneNumber) return { success: false, status: WHATSAPP.STATUS.FAILED, message: 'No phone number' };
    var fullNumber = String(phoneNumber || '');
    if (fullNumber.indexOf('@') !== -1) {
      /* chat ID — pass through unchanged */
    } else if (fullNumber.startsWith('+')) {
      /* already E.164 — pass through unchanged */
    } else if (fullNumber.startsWith('00')) {
      var cc = settings.defaultCountryCode || WHATSAPP.DEFAULTS.DEFAULT_COUNTRY_CODE;
      var stripped00 = fullNumber.replace(/^0+/, '');
      fullNumber = (cc && stripped00.indexOf(cc) === 0) ? '+' + stripped00 : '+' + cc + stripped00;
    } else {
      var cc = settings.defaultCountryCode || WHATSAPP.DEFAULTS.DEFAULT_COUNTRY_CODE;
      fullNumber = (cc && fullNumber.indexOf(cc) === 0) ? '+' + fullNumber : '+' + cc + fullNumber.replace(/^0+/, '');
    }
    var result = whatsappProviderSend(settings, fullNumber, messageBody);
    var status = result.success ? WHATSAPP.STATUS.SENT : WHATSAPP.STATUS.FAILED;
    var waId = whatsappLog(result.messageId || '', recipientName || '', fullNumber, module || '', refId || '', templateName || '', status, settings.provider, result.success ? '' : result.message, sentBy || Session.getActiveUser().getEmail(), idempotencyKey || '');
    return { success: result.success, status: status, messageId: result.messageId, logId: waId, message: result.message };
  } catch (e) {
    whatsappLog('', recipientName || '', phoneNumber || '', module || '', refId || '', templateName || '', WHATSAPP.STATUS.FAILED, '', e.message, sentBy || Session.getActiveUser().getEmail(), idempotencyKey || '');
    return { success: false, status: WHATSAPP.STATUS.FAILED, message: e.message };
  }
}

function whatsappGetTemplateByEvent(eventType) {
  var templates = getAllData(WHATSAPP.TEMPLATES_SHEET) || [];
  for (var i = 0; i < templates.length; i++) {
    if (templates[i].EventType === eventType) return templates[i];
  }
  return null;
}

function whatsappSendNotification(eventType, data) {
  try {
    var settings = whatsappGetSettings();
    if (!settings.enabled) return { success: false, status: WHATSAPP.STATUS.PENDING, message: 'WhatsApp disabled' };
    var messageBody;
    if (data.__body) {
      messageBody = data.__body;
    } else {
      whatsappInitTemplatesSheet();
      var template = whatsappGetTemplateByEvent(eventType);
      if (!template) {
        return { success: false, status: WHATSAPP.STATUS.FAILED, message: 'No template for event: ' + eventType };
      }
      messageBody = whatsappFormatMessage(template.TemplateBody, data);
    }
    var phoneField = data.phone || data.mobile || '';
    var phones = [];
    if (phoneField) {
      phones = [phoneField];
    } else if (data.phoneNumbers) {
      phones = Array.isArray(data.phoneNumbers) ? data.phoneNumbers : [data.phoneNumbers];
    }
    if (phones.length === 0) {
      return { success: false, status: WHATSAPP.STATUS.PENDING, message: 'No phone numbers provided' };
    }
    var refId = data.jobCardNo || data.pmNumber || data.partCode || data.grnNo || data.userId || data.id || '';
    var module = data.module || '';
    var idemKey = data._idempotencyKey || '';
    var results = [];
    phones.forEach(function(phone) {
      var result = whatsappSendMessage(phone, messageBody, module, refId, eventType, data.recipientName || data.name || '', '', idemKey);
      results.push(result);
    });
    return { success: results.length > 0, results: results };
  } catch (e) {
    return { success: false, status: WHATSAPP.STATUS.FAILED, message: e.message };
  }
}

function whatsappGetUserPhone(email) {
  if (!email) return '';
  var users = getAllData(CONFIG.SHEET_NAMES.USERS) || [];
  for (var i = 0; i < users.length; i++) {
    if (users[i].Email === email) return users[i].Mobile || '';
  }
  var techs = getAllData(CONFIG.SHEET_NAMES.TECHNICIANS) || [];
  for (var j = 0; j < techs.length; j++) {
    if (techs[j].Email === email) return techs[j].Mobile || '';
  }
  return '';
}

function whatsappGetAdminPhones() {
  var phones = [];
  var users = getAllData(CONFIG.SHEET_NAMES.USERS) || [];
  users.forEach(function(u) {
    if ((u.IsAdmin === 'TRUE' || u.IsAdmin === true || u.Role === 'Admin') && u.Mobile) {
      phones.push(u.Mobile);
    }
  });
  return phones;
}

function whatsappGetStorePhones() {
  var phones = [];
  var users = getAllData(CONFIG.SHEET_NAMES.USERS) || [];
  users.forEach(function(u) {
    if ((u.Role === 'Store' || u.CanManageInventory === 'TRUE') && u.Mobile) {
      phones.push(u.Mobile);
    }
  });
  return phones;
}

function whatsappGetTechPhone(email) {
  if (!email) return '';
  var techs = getAllData(CONFIG.SHEET_NAMES.TECHNICIANS) || [];
  for (var i = 0; i < techs.length; i++) {
    if (techs[i].Email === email) return techs[i].Mobile || '';
  }
  var users = getAllData(CONFIG.SHEET_NAMES.USERS) || [];
  for (var j = 0; j < users.length; j++) {
    if (users[j].Email === email) return users[j].Mobile || '';
  }
  return '';
}

function whatsappTestSend(data) {
  try {
    var user = requireUserPermission('CanManageWhatsApp', data);
    var settings = whatsappGetSettings();
    if (!settings.enabled) return { success: false, message: 'WhatsApp is disabled. Enable it in settings first.' };
    var configIssue = whatsappConfigIssue(settings);
    if (configIssue) return { success: false, message: configIssue };
    var phone = String((data && (data.testPhone || data.phone)) || settings.testPhone || '').replace(/[^0-9+]/g, '');
    if (!phone || phone.length < 10) {
      return { success: false, message: 'Invalid test phone number. Must be at least 10 digits.' };
    }
    var msg = String((data && (data.testMessage || data.message)) || settings.testMessage || '').trim();
    if (!msg) return { success: false, message: 'Test message cannot be empty.' };
    var company = settings.companyName || WHATSAPP.DEFAULTS.COMPANY_NAME;
    var fullMsg = '*Test Message from ' + company + '*\n\n' + msg + '\n\nSent: ' + getCurrentTimestamp();
    var sentBy = (user && user.Email) || (data && data._userEmail) || '';
    var recipientName = (data && (data._userName || data.recipientName)) || sentBy || '';
    var result = whatsappSendMessage(phone, fullMsg, 'System', '', 'TestMessage', recipientName, sentBy);
    return result;
  } catch (e) {
    return { success: false, message: e.message };
  }
}

function whatsappMetaIdValid(v) {
  v = String(v || '').trim();
  return /^\d+$/.test(v) && v.length >= 14 && v.length <= 20;
}

function whatsappTwilioSidValid(v) {
  v = String(v || '').trim();
  return /^AC[0-9a-fA-F]{32}$/.test(v);
}

function whatsappTwilioSenderValid(v) {
  v = String(v || '').trim();
  return /^\+[1-9][0-9]{6,14}$/.test(v);
}

function whatsappEndpointBelongsTo(settings, provider) {
  var ep = String(settings.apiEndpoint || '').trim();
  if (provider === 'twilio') return ep.indexOf('api.twilio.com') !== -1 && ep.indexOf('graph.facebook.com') === -1 && ep.indexOf('api.ultramsg.com') === -1;
  if (provider === 'meta') return ep.indexOf('graph.facebook.com') !== -1 && ep.indexOf('api.twilio.com') === -1 && ep.indexOf('api.ultramsg.com') === -1;
  if (provider === 'ultramsg') return ep.indexOf('api.ultramsg.com') !== -1 && ep.indexOf('graph.facebook.com') === -1 && ep.indexOf('api.twilio.com') === -1;
  return true;
}

function whatsappConfigIssue(settings) {
  if (settings.provider === 'meta') {
    if (settings.apiEndpoint && !whatsappEndpointBelongsTo(settings, 'meta')) return 'Meta API Endpoint must be the Meta Graph API endpoint (graph.facebook.com), not a Twilio endpoint.';
    if (!settings.apiToken) return 'Meta API token is not configured.';
    if (!settings.phoneNumberId) return 'Meta Phone Number ID is not configured.';
    if (!whatsappMetaIdValid(settings.phoneNumberId)) return 'Meta Phone Number ID looks invalid. It must be the numeric ID from Meta (e.g. 106540352242922), not the phone number.';
    if (!settings.businessAccountId) return 'Meta Business Account ID is not configured.';
    if (!whatsappMetaIdValid(settings.businessAccountId)) return 'Meta Business Account ID looks invalid. It must be the numeric WhatsApp Business Account ID (e.g. 375420581369195).';
  } else if (settings.provider === 'twilio') {
    if (settings.apiEndpoint && !whatsappEndpointBelongsTo(settings, 'twilio')) return 'Twilio API Endpoint must point to api.twilio.com, not the Meta Graph API endpoint (graph.facebook.com).';
    if (!settings.apiToken) return 'Twilio Auth Token is not configured.';
    if (!settings.businessAccountId) return 'Twilio Account SID is not configured.';
    if (!whatsappTwilioSidValid(settings.businessAccountId)) return 'Twilio Account SID looks invalid. It must start with "AC" followed by 32 hex characters (e.g. ACxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx), not a Meta Business Account ID.';
    if (!settings.phoneNumberId) return 'Twilio WhatsApp sender (From) is not configured.';
    if (!whatsappTwilioSenderValid(settings.phoneNumberId)) return 'Twilio WhatsApp sender (From) looks invalid. It must be an E.164 phone number with a leading + (e.g. +14155238886), not a Meta Phone Number ID.';
  } else if (settings.provider === 'ultramsg') {
    if (settings.apiEndpoint && !whatsappEndpointBelongsTo(settings, 'ultramsg')) return 'UltraMsg API URL must point to api.ultramsg.com, not a Meta or Twilio endpoint.';
    var uInstanceId = (settings.ultramsg && settings.ultramsg.instanceId) || settings.instanceId || '';
    var uToken = (settings.ultramsg && settings.ultramsg.token) || settings.apiToken || '';
    if (!uInstanceId) return 'UltraMsg Instance ID is not configured.';
    if (!uToken) return 'UltraMsg Token is not configured.';
  } else {
    return 'Unknown WhatsApp provider: ' + settings.provider;
  }
  return '';
}

function whatsappAuthProbe(data) {
  try {
    requireUserPermission('CanManageWhatsApp', data);
    var settings = whatsappGetSettings();
    var r = authorizeExternalRequest();
    var status = r.success
      ? 'External API access is authorized.'
      : (r.message || ('External API request failed with status ' + r.code + '. Apps Script does not have the required external request (script.external_request) permission.'));
    return {
      success: !!r.success,
      code: r.code,
      provider: settings.provider,
      message: status
    };
  } catch (e) {
    return { success: false, message: e.message };
  }
}

function whatsappGetSettingsData(data) {
  try {
    requireUserPermission('CanManageWhatsApp', data);
  } catch (e) {
    return { success: false, message: e.message };
  }
  return {
    success: true,
    settings: whatsappGetSettings(),
    templates: whatsappGetTemplates(),
    stats: whatsappGetDashboardStats(),
    logs: whatsappGetLogs({ limit: 50 })
  };
}

function whatsappSendJobStatusNotification(eventType, jobData) {
  try {
    return whatsappSendJobCardEvent(eventType, jobData);
  } catch (e) {
    return { success: false, status: WHATSAPP.STATUS.FAILED, message: e.message };
  }
}

function whatsappJcePick(src, keys) {
  for (var i = 0; i < keys.length; i++) {
    var v = src[keys[i]];
    if (v !== undefined && v !== null && v !== '') return v;
  }
  return '';
}

function whatsappJceRow(label, value) {
  if (value === undefined || value === null) return '';
  var s = String(value).trim();
  if (s === '') return '';
  return label + s + '\n';
}

function whatsappJceSection(title, lines) {
  var body = '';
  for (var i = 0; i < lines.length; i++) if (lines[i]) body += lines[i];
  if (body === '') return '';
  return '*' + title + '*\n' + body + '\n';
}

function whatsappJceName(email) {
  if (!email) return '';
  var e = String(email).trim();
  if (!e || e.indexOf('@') === -1) return e;
  var users = (typeof getAllData === 'function') ? (getAllData(CONFIG.SHEET_NAMES.USERS) || []) : [];
  for (var i = 0; i < users.length; i++) {
    if (users[i].Email === e) return users[i].Name || e;
  }
  var techSheet = (CONFIG.SHEET_NAMES && CONFIG.SHEET_NAMES.TECHNICIANS) || '';
  if (techSheet) {
    var techs = (typeof getAllData === 'function') ? (getAllData(techSheet) || []) : [];
    for (var j = 0; j < techs.length; j++) {
      if (techs[j].Email === e) return techs[j].Name || e;
    }
  }
  return e;
}

function whatsappJceNames(csv) {
  if (!csv) return '';
  var out = [];
  String(csv).split(',').forEach(function(p) {
    var n = whatsappJceName(p.trim());
    if (n) out.push(n);
  });
  return out.join(', ');
}

function whatsappJceDuration(v) {
  if (v === undefined || v === null || v === '') return '';
  var s = String(v).trim();
  if (s === '') return '';
  if (s.indexOf(':') !== -1 || /^\d+[dD]/.test(s)) return s;
  var mins = parseFloat(s) || 0;
  if (typeof durationToDisplay === 'function') return durationToDisplay(mins);
  var h = Math.floor(mins / 60);
  var m = Math.floor(mins % 60);
  return (h < 10 ? '0' : '') + h + ':' + (m < 10 ? '0' : '') + m;
}

function whatsappJceMaterials(spareParts) {
  if (!spareParts) return [];
  var s = String(spareParts).trim();
  if (!s) return [];
  var items = [];
  if (s.charAt(0) === '[') {
    try {
      var arr = JSON.parse(s);
      if (Array.isArray(arr)) {
        arr.forEach(function(m) {
          if (m && (m.partName || m.material || m.name || m.partCode)) {
            var line = '🔩 Material: ' + (m.partName || m.material || m.name || m.partCode || '');
            if (m.quantity !== undefined && m.quantity !== null && m.quantity !== '') line += ' / Quantity: ' + m.quantity;
            if (m.unit) line += ' / Unit: ' + m.unit;
            items.push(line);
          }
        });
      }
    } catch (e) { items = []; }
  }
  if (items.length === 0) {
    String(s).split(/\r?\n/).forEach(function(ln) {
      var t = ln.trim();
      if (t) items.push('🔩 ' + t);
    });
  }
  return items;
}

function whatsappJceCollectPhones(jc) {
  var phones = [];
  function add(p) {
    if (p && phones.indexOf(p) === -1) phones.push(p);
  }
  if (jc.phoneNumbers) {
    var pn = Array.isArray(jc.phoneNumbers) ? jc.phoneNumbers : [jc.phoneNumbers];
    pn.forEach(add);
  }
  if (jc.phone) add(jc.phone);
  if (jc.customerPhone) add(jc.customerPhone);
  if (jc.assignedEmails) String(jc.assignedEmails).split(',').forEach(function(e) { add(whatsappGetUserPhone(e.trim())); });
  if (jc.complaintEmail) add(whatsappGetUserPhone(jc.complaintEmail));
  if (jc.approverEmail) add(whatsappGetUserPhone(jc.approverEmail));
  return phones;
}

function whatsappJceNormalize(jc) {
  var src = {};
  for (var k in jc) src[k] = jc[k];
  if (!src.JobCardNo && src.jobCardNo && typeof getJobCard === 'function') {
    try {
      var rec = getJobCard(src.jobCardNo);
      if (rec) { for (var r in rec) if (src[r] === undefined) src[r] = rec[r]; }
    } catch (e) {}
  }
  return {
    jobCardNo: whatsappJcePick(src, ['JobCardNo', 'jobCardNo']),
    currentStatus: whatsappJcePick(src, ['CurrentStatus', 'currentStatus']),
    opened: whatsappJcePick(src, ['OpenDateTime', 'opened']),
    started: whatsappJcePick(src, ['StartDateTime', 'startTime', 'started']),
    pending: whatsappJcePick(src, ['PendingDateTime', 'pending']),
    approved: whatsappJcePick(src, ['ApprovedDateTime', 'approved']),
    closed: whatsappJcePick(src, ['CloseDateTime', 'closed']),
    section: whatsappJcePick(src, ['Section', 'section']),
    department: whatsappJcePick(src, ['Department', 'department']),
    machine: whatsappJcePick(src, ['Machine', 'machine']),
    machineNumber: whatsappJcePick(src, ['MachineNumber', 'machineNumber']),
    machineId: whatsappJcePick(src, ['MachineID', 'machineId']),
    assetId: whatsappJcePick(src, ['AssetID', 'assetId']),
    category: whatsappJcePick(src, ['ComplaintCategory', 'category']),
    issue: whatsappJcePick(src, ['ComplaintDescription', 'issue', 'complaint']),
    priority: whatsappJcePick(src, ['Priority', 'priority']),
    breakdownType: whatsappJcePick(src, ['BreakdownType', 'breakdownType']),
    rootCause: whatsappJcePick(src, ['RootCause', 'rootCause']),
    correctiveAction: whatsappJcePick(src, ['CorrectiveAction', 'correctiveAction']),
    finalRemarks: whatsappJcePick(src, ['FinalRemarks', 'remarks', 'finalRemarks']),
    initialRemarks: whatsappJcePick(src, ['InitialRemarks', 'initialRemarks']),
    pendingRemarks: whatsappJcePick(src, ['PendingRemarks', 'pendingRemarks']),
    approvalStatus: whatsappJcePick(src, ['ApprovalStatus', 'approvalStatus']),
    approvalRemarks: whatsappJcePick(src, ['ApprovalRemarks', 'approvalRemarks']),
    maintenanceTeam: whatsappJcePick(src, ['MaintenanceTeam', 'maintenanceTeam']),
    reportedBy: whatsappJceName(whatsappJcePick(src, ['ComplaintBy', 'ComplaintByEmail', 'reportedBy', 'complaintByEmail'])),
    assignedTo: whatsappJceNames(whatsappJcePick(src, ['AssignedTechnician', 'assignedTech', 'assignedTechEmail'])),
    startedBy: whatsappJceName(whatsappJcePick(src, ['StartedBy', 'startedBy'])),
    pendingBy: whatsappJceName(whatsappJcePick(src, ['PendingBy', 'pendingBy'])),
    approvedBy: whatsappJceName(whatsappJcePick(src, ['ApprovedBy', 'approvedBy'])),
    closedBy: whatsappJceName(whatsappJcePick(src, ['ClosedBy', 'closedBy'])),
    createdBy: whatsappJceName(whatsappJcePick(src, ['CreatedBy', 'createdBy'])),
    updatedBy: whatsappJceName(whatsappJcePick(src, ['UpdatedBy', 'updatedBy'])),
    workingTime: whatsappJceDuration(whatsappJcePick(src, ['WorkingTime', 'workingTime'])),
    downtime: whatsappJceDuration(whatsappJcePick(src, ['Downtime', 'downtime'])),
    totalDuration: whatsappJceDuration(whatsappJcePick(src, ['TotalDuration', 'totalDuration'])),
    spareParts: whatsappJcePick(src, ['SpareParts', 'spareParts']),
    assignedEmails: whatsappJcePick(src, ['AssignedTechnician', 'assignedTechEmail', 'assignedTech']),
    complaintEmail: whatsappJcePick(src, ['ComplaintByEmail', 'ComplaintBy', 'complaintByEmail', 'reportedByEmail']),
    approverEmail: whatsappJcePick(src, ['ApprovedBy', 'approverEmail']),
    customerPhone: whatsappJcePick(src, ['customerPhone']),
    phone: whatsappJcePick(src, ['phone']),
    phoneNumbers: whatsappJcePick(src, ['phoneNumbers']),
    module: whatsappJcePick(src, ['module']),
    recipientName: whatsappJcePick(src, ['recipientName', 'name'])
  };
}

function whatsappBuildJobCardBody(eventType, jc, company) {
  var ev = WHATSAPP_JCE.EVENTS[eventType];
  var sep = WHATSAPP_JCE.SEP;
  var b = '';
  b += sep + '\n';
  b += ev.emoji + ' *' + ev.label.toUpperCase() + '*\n';
  b += sep + '\n';
  b += '🏢 *' + company + '*\n\n';

  var info = [whatsappJceRow('📇 Job Card: ', jc.jobCardNo), whatsappJceRow('📊 Status: ', jc.currentStatus)];
  if (ev.timestamp === 'opened') info.push(whatsappJceRow('📅 Opened: ', jc.opened));
  if (ev.timestamp === 'started') info.push(whatsappJceRow('▶️ Started: ', jc.started));
  if (ev.timestamp === 'pending') info.push(whatsappJceRow('⏳ Pending Since: ', jc.pending));
  if (ev.timestamp === 'approved') info.push(whatsappJceRow('✅ Approved: ', jc.approved));
  if (ev.timestamp === 'closed') info.push(whatsappJceRow('🔒 Closed: ', jc.closed));
  b += whatsappJceSection('JOB CARD INFORMATION', info);

  var details = [
    whatsappJceRow('🏭 Section: ', jc.section),
    whatsappJceRow('🏗️ Department: ', jc.department),
    whatsappJceRow('⚙️ Machine: ', jc.machine),
    whatsappJceRow('🔢 Machine Number: ', jc.machineNumber),
    whatsappJceRow('📌 Machine ID: ', jc.machineId),
    whatsappJceRow('🔖 Asset ID: ', jc.assetId),
    whatsappJceRow('🏷️ Category: ', jc.category)
  ];
  if (jc.issue) details.push('⚠️ *Issue:* ' + jc.issue + '\n');
  details.push(whatsappJceRow('🎯 Priority: ', jc.priority));
  if (eventType === WHATSAPP.TEMPLATES.JC_CLOSED) {
    details.push(whatsappJceRow('🔨 Breakdown Type: ', jc.breakdownType));
    details.push(whatsappJceRow('🩺 Root Cause: ', jc.rootCause));
    if (jc.correctiveAction) details.push('✅ *Resolution:* ' + jc.correctiveAction + '\n');
    details.push(whatsappJceRow('📝 Final Remarks: ', jc.finalRemarks));
    details.push(whatsappJceRow('⏱️ Working Time: ', jc.workingTime));
    details.push(whatsappJceRow('📉 Downtime: ', jc.downtime));
    details.push(whatsappJceRow('🕓 Total Duration: ', jc.totalDuration));
  }
  b += whatsappJceSection('MAINTENANCE DETAILS', details);

  var resp = [
    whatsappJceRow('🛠️ Maintenance Team: ', jc.maintenanceTeam),
    whatsappJceRow('🧑‍🔧 Reported By: ', jc.reportedBy),
    whatsappJceRow('👤 Assigned To: ', jc.assignedTo),
    whatsappJceRow('▶️ Started By: ', jc.startedBy),
    whatsappJceRow('⏳ Pending By: ', jc.pendingBy),
    whatsappJceRow('✅ Approved By: ', jc.approvedBy),
    whatsappJceRow('🔒 Closed By: ', jc.closedBy)
  ];
  b += whatsappJceSection('RESPONSIBILITY', resp);

  var action = [ev.emoji + ' ' + ev.action + '\n'];
  if (eventType === WHATSAPP.TEMPLATES.JC_OPENED && jc.initialRemarks) action.push('📝 Remarks: ' + jc.initialRemarks + '\n');
  if (eventType === WHATSAPP.TEMPLATES.JC_PENDING && jc.pendingRemarks) action.push('📝 Remarks: ' + jc.pendingRemarks + '\n');
  if (eventType === WHATSAPP.TEMPLATES.JC_APPROVED && jc.approvalRemarks) action.push('📝 Remarks: ' + jc.approvalRemarks + '\n');
  b += whatsappJceSection('ACTION', action);

  var mats = whatsappJceMaterials(jc.spareParts);
  if (mats.length > 0) {
    b += '*MATERIAL / PARTS USED*\n';
    mats.forEach(function(m) { b += m + '\n'; });
    b += '\n';
  }

  var sys = [
    whatsappJceRow('💾 Created By: ', jc.createdBy),
    whatsappJceRow('👤 Updated By: ', jc.updatedBy),
    whatsappJceRow('🔔 Notification: ', ev.label),
    whatsappJceRow('🕒 Generated: ', getCurrentTimestamp())
  ];
  b += whatsappJceSection('SYSTEM', sys);

  b += '*NEXT ACTION*\n';
  b += '🎯 ' + ev.next + '\n\n';
  b += '🤖 Generated by ' + company + ' | 🏢 ' + WHATSAPP_JCE.FOOTER_COMPANY + '\n';
  b += sep;
  return b;
}

function whatsappFindSentLogByKey(key) {
  if (!key) return null;
  try {
    invalidateCache(WHATSAPP.SHEET);
    var logs = getAllData(WHATSAPP.SHEET) || [];
    for (var i = logs.length - 1; i >= 0; i--) {
      if (String(logs[i].IdempotencyKey || '') === key && String(logs[i].Status || '') === WHATSAPP.STATUS.SENT) {
        return logs[i];
      }
    }
  } catch (e) {}
  return null;
}

function whatsappSendJobCardEvent(eventType, jobCardData) {
  try {
    if (!jobCardData) return { success: false, status: WHATSAPP.STATUS.FAILED, message: 'Missing job card data' };
    if (!WHATSAPP_JCE.EVENTS[eventType]) return { success: false, status: WHATSAPP.STATUS.FAILED, message: 'Unsupported job card event: ' + eventType };
    var jc = whatsappJceNormalize(jobCardData);
    if (!jc.jobCardNo) return { success: false, status: WHATSAPP.STATUS.FAILED, message: 'Missing job card number' };
    var key = eventType + '|' + jc.jobCardNo;
    if (WHATSAPP_JCE_SENT[key]) {
      return { success: false, status: 'DUPLICATE', deduplicated: true, message: 'WhatsApp notification already sent for this job card event' };
    }
    var lock = LockService.getScriptLock();
    try { lock.waitLock(5000); } catch (lockErr) {
      return { success: false, status: 'LOCKED', message: 'Could not acquire deduplication lock' };
    }
    try {
      var existing = whatsappFindSentLogByKey(key);
      if (existing) {
        WHATSAPP_JCE_SENT[key] = true;
        return { success: false, status: 'DUPLICATE', deduplicated: true, message: 'WhatsApp notification already sent (persistent dedup)', logId: existing.MessageID };
      }
    } finally {
      lock.releaseLock();
    }
    var company = WHATSAPP.DEFAULTS.COMPANY_NAME;
    try { company = whatsappGetSettings().companyName || company; } catch (e) {}
    var payload = {
      jobCardNo: jc.jobCardNo,
      module: jc.module || 'Jobs',
      phoneNumbers: whatsappJceCollectPhones(jc),
      recipientName: jc.recipientName || '',
      __body: whatsappBuildJobCardBody(eventType, jc, company),
      _idempotencyKey: key
    };
    var result = whatsappSendNotification(eventType, payload);
    WHATSAPP_JCE_SENT[key] = true;
    return result;
  } catch (e) {
    return { success: false, status: WHATSAPP.STATUS.FAILED, message: e.message };
  }
}

function whatsappSendStockAlertNotification(eventType, partData) {
  try {
    if (!partData) return { success: false, status: WHATSAPP.STATUS.FAILED, message: 'Missing part data' };
    var payload = {
      partCode: partData.partCode || partData.code || '',
      partName: partData.partName || partData.name || '',
      currentStock: partData.currentStock || partData.stock || partData.quantity || 0,
      minStock: partData.minStock || partData.minimumStock || 0,
      reorderLevel: partData.reorderLevel || partData.minimumQty || 0,
      unit: partData.unit || '',
      storeLocation: partData.storeLocation || partData.location || '',
      phoneNumbers: whatsappGetStorePhones(),
      module: 'Inventory'
    };
    return whatsappSendNotification(eventType, payload);
  } catch (e) {
    return { success: false, status: WHATSAPP.STATUS.FAILED, message: e.message };
  }
}

function whatsappGetJcePreviews(data) {
  try {
    requireUserPermission('CanManageWhatsApp', data);
    var company = WHATSAPP.DEFAULTS.COMPANY_NAME;
    try { company = whatsappGetSettings().companyName || company; } catch (e) {}

    var sample = {
      JobCardNo: 'JC-2026-000001',
      CurrentStatus: 'Pending',
      OpenDateTime: '2026-08-16 09:15:00',
      StartDateTime: '2026-08-16 09:40:00',
      PendingDateTime: '2026-08-16 11:05:00',
      ApprovedDateTime: '2026-08-16 11:50:00',
      CloseDateTime: '2026-08-16 12:10:00',
      Section: 'Drawing Section',
      Department: 'Maintenance',
      Machine: 'Straightener',
      MachineNumber: 'MCH-0042',
      MachineID: 'mch0042',
      AssetID: 'AST-0007',
      ComplaintCategory: 'Mechanical',
      ComplaintDescription: 'Excessive vibration and bearing noise during operation',
      Priority: 'High',
      BreakdownType: 'Mechanical',
      RootCause: 'Worn drive bearing',
      CorrectiveAction: 'Replaced defective bearing and realigned the drive shaft',
      FinalRemarks: 'Machine returned to service after a successful test run',
      InitialRemarks: 'Reported at the start of the shift',
      PendingRemarks: 'Submitted for supervisor review',
      ApprovalStatus: 'Approved',
      ApprovalRemarks: 'Work quality verified and approved',
      MaintenanceTeam: 'Maintenance Team A',
      ComplaintBy: 'Muhammad Rizwan',
      AssignedTechnician: 'Ali Hassan',
      StartedBy: 'Ali Hassan',
      PendingBy: 'Ali Hassan',
      ApprovedBy: 'Supervisor Afsar',
      ClosedBy: 'Supervisor Afsar',
      SpareParts: 'Bearing 6205-ZZ (SPR-0011) x 2, EP-2 Grease (SPR-0012) x 1'
    };

    var jc = whatsappJceNormalize(sample);
    var events = [];
    var keys = Object.keys(WHATSAPP_JCE.EVENTS);
    for (var i = 0; i < keys.length; i++) {
      var ev = keys[i];
      var meta = WHATSAPP_JCE.EVENTS[ev];
      events.push({
        eventType: ev,
        label: meta.label,
        emoji: meta.emoji,
        action: meta.action,
        next: meta.next,
        __body: whatsappBuildJobCardBody(ev, jc, company)
      });
    }
    return { success: true, company: company, events: events };
  } catch (e) {
    return { success: false, message: e.message, events: [] };
  }
}

/* =====================================================================
   TEST-ONLY SEED: Create a single hardcoded test Job Card for
   WhatsApp lifecycle testing. Bypasses the normal card creation path
   to avoid triggering notification hooks.
   Permission-gated: CanManageWhatsApp + Admin only.
   ===================================================================== */
function whatsappSeedTestJobCard(data) {
  try {
    requireUserPermission('CanManageWhatsApp', data);

    var user = apiCallerUser(data);
    if (!user || (user.Role !== 'Admin' && user.Role !== 'Administrator' && user.IsAdmin !== 'TRUE' && user.IsAdmin !== true)) {
      return { success: false, message: 'Only Admin can seed test job cards.' };
    }

    var TEST_CARD_NO = 'JC-TEST-WA-001';
    var existing = getRecordById(CONFIG.SHEET_NAMES.JOBCARDS, 'JobCardNo', TEST_CARD_NO);
    if (existing) {
      return {
        success: false,
        message: 'Test card ' + TEST_CARD_NO + ' already exists.',
        jobCardNo: TEST_CARD_NO,
        currentStatus: existing.CurrentStatus || existing.Status || 'UNKNOWN'
      };
    }

    var now = formatDateTimeISO(new Date());
    var row = {
      JobCardNo: TEST_CARD_NO,
      OpenDateTime: now,
      Section: 'Maintenance',
      Department: 'Facility Maintenance',
      Machine: 'TEST-MACHINE-LIFECYCLE',
      AssetID: '',
      ComplaintCategory: 'Wear & Tear',
      ComplaintBy: 'QA Tester',
      ComplaintDescription: 'WHATSAPP LIFECYCLE TEST — DO NOT TREAT AS REAL WORK',
      Priority: 'Low',
      FaultImage: '',
      CreatedBy: data._userEmail || '',
      CreatedAt: getCurrentTimestamp(),
      AssignedTechnician: '',
      StartedBy: '',
      StartDateTime: '',
      WaitingTime: 0,
      InitialRemarks: '',
      MaintenanceTeam: '',
      RootCause: '',
      CorrectiveAction: '',
      SpareParts: '',
      RepairImage: '',
      FinalRemarks: '',
      ClosedBy: '',
      CloseDateTime: '',
      WorkingTime: 0,
      Downtime: 0,
      TotalDuration: 0,
      BreakdownType: '',
      PendingDateTime: '',
      PendingBy: '',
      PendingRemarks: '',
      ApprovalStatus: '',
      ApprovedBy: '',
      ApprovedDateTime: '',
      ApprovalRemarks: '',
      ReturnedBy: '',
      ReturnedDateTime: '',
      ReturnReason: '',
      UpdatedBy: data._userEmail || '',
      UpdatedAt: getCurrentTimestamp(),
      CurrentStatus: 'OPEN',
      ComplaintByCode: '',
      ComplaintByEmail: 'watester@cmms.com',
      AssignedTechnicianIDs: '',
      QRCode: '',
      Barcode: '',
      QRGeneratedDate: '',
      MachineNumber: '',
      MachineID: ''
    };

    addRow(CONFIG.SHEET_NAMES.JOBCARDS, row);

    return {
      success: true,
      jobCardNo: TEST_CARD_NO,
      currentStatus: 'OPEN',
      recipientPhone: '3152340889',
      created: true,
      message: 'TEST-ONLY seed card created. This is not a real job card.'
    };
  } catch (e) {
    return { success: false, message: e.message };
  }
}
